//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCLFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobStatu
    {
        public int JobStatusID { get; set; }
        public int RentalID { get; set; }
        public int Status { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastEditor { get; set; }
    
        public virtual tblRentalJobInfo tblRentalJobInfo { get; set; }
        public virtual tblStatusInfo tblStatusInfo { get; set; }
    }
}
