//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCLFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRentalTagRange
    {
        public int TagRangeID { get; set; }
        public int RentalID { get; set; }
        public int TagValFrom { get; set; }
        public int TagValTo { get; set; }
        public Nullable<int> GroupRangeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Seq { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblRentalJobInfo tblRentalJobInfo { get; set; }
        public virtual tblRentalTagRange tblRentalTagRange1 { get; set; }
        public virtual tblRentalTagRange tblRentalTagRange2 { get; set; }
    }
}
