//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCLFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRentalDLPMStoreLink
    {
        public int RecID { get; set; }
        public int UserID { get; set; }
        public string StoreNo { get; set; }
        public string email { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Lastedit { get; set; }
        public string LastEditor { get; set; }
    }
}
