//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCLFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRentalJobInfo
    {
        public tblRentalJobInfo()
        {
            this.tblJobStatus = new HashSet<tblJobStatu>();
            this.tblRentalFileInfoes = new HashSet<tblRentalFileInfo>();
            this.tblRentalTagRanges = new HashSet<tblRentalTagRange>();
        }
    
        public int RentalID { get; set; }
        public int JobNo { get; set; }
        public System.DateTime JobDateTime { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string CustNo { get; set; }
        public string OfficeNo { get; set; }
        public string MOR { get; set; }
        public string MOREmail { get; set; }
        public long SoftwareID { get; set; }
        public long SoftwareVer { get; set; }
        public string StoreNo { get; set; }
        public string StoreName { get; set; }
    
        public virtual ICollection<tblJobStatu> tblJobStatus { get; set; }
        public virtual ICollection<tblRentalFileInfo> tblRentalFileInfoes { get; set; }
        public virtual ICollection<tblRentalTagRange> tblRentalTagRanges { get; set; }
    }
}
