//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCLFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data;

    public partial class tblRentalTagRange
    {
        [Required]
        [HiddenInput(DisplayValue = false)]
        public int TagRangeID { get; set; }
        [Required]
        [HiddenInput(DisplayValue = false)]
        public int RentalID { get; set; }
        [Required]
        [Display(Name = "From")]
        [Range(1, 9999)]
        public int TagValFrom { get; set; }
        [Required]
        [Display(Name = "To")]
        [Range(1, 9999)]
        public int TagValTo { get; set; }
        public Nullable<int> GroupRangeID { get; set; }
        public string Name { get; set; }
        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }
        public Nullable<int> Seq { get; set; }
        public bool Deleted { get; set; }

        public virtual tblRentalJobInfo tblRentalJobInfo { get; set; }
        public virtual tblRentalTagRange tblRentalTagRange1 { get; set; }
        public virtual tblRentalTagRange tblRentalTagRange2 { get; set; }
    }

    public class JobListforDLPM
    {
        public DataTable JobList { get; set; }
    }

    public class ListOfUploadedFiles
    {
        public DataTable FileList { get; set; }
    }

    public class ListOfUploadedFilesErrors
    {
        public DataTable ErrorList { get; set; }
    }
}
