//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCLFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRentalFileInfo
    {
        public int RentalFileTXID { get; set; }
        public int RentalID { get; set; }
        public string TXFileName { get; set; }
        public bool Deleted { get; set; }
        public int LoginID { get; set; }
        public bool JobNoMismatch { get; set; }
        public bool InvalidFile { get; set; }
        public Nullable<long> Lines { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<long> Ext { get; set; }
    
        public virtual tblRentalFileInfo tblRentalFileInfo1 { get; set; }
        public virtual tblRentalFileInfo tblRentalFileInfo2 { get; set; }
        public virtual tblRentalJobInfo tblRentalJobInfo { get; set; }
    }
}
