//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCLFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserInfo
    {
        public int LoginID { get; set; }
        public string UserName { get; set; }
    
        public virtual webpages_Membership webpages_Membership { get; set; }
    }
}
